### ISSUE TITLE
Dependency from JVM

### ISSUE THREAD

**Issue by CristianMG** [KotlinGeekDev/kostr#8]
Hi,

I like this project because I like Kotlin and I like the Nostro project. I would like to propose something, although the project is in the early stage. I can see a big problem: the standard of the Kotlin projects library is migrating to Kotlin native, which means that Kotlin native projects have no dependencies on the Java virtual machine. This project has dependencies on the JVM, which I think could be changed for another dependency that does not depend on the JVM, like Kotlin serialization. Nowadays, we have a lot of alternatives in Kotlin native for each library.

For example, we could use SQLDelight for the database and Kotlin Serialization for Jackson. And there are many more options. What do you think about migrating the project to Kotlin Multiplatform? This would allow the library to be used on different platforms, such as iOS, JavaScript, Kotlin Native, and of course the JVM.

I would like to participate in this project in these terms, if you would like, of course. There is a lot of work to be done, and I would like to know your point of view before working on a pull request.

Here is a link to more information about Kotlin native: https://kotlinlang.org/docs/native-overview.html

Greetings.

**Comment by KotlinGeekDev** [comment]
Hello Cristian. Of course, I am a fan of KMP, was one of the people who was an enthusiast from the moment of it's conception. :sweat_smile: And you're right. We could even use Ktor for Websockets. However, I don't have enough resources to turn it into a KMP library(until I am done with Nosky's base functionality). But I would like it to go in that direction. So feel free to drop PRs.

**Comment by CristianMG** [comment]
Ok, I understand the problem, if you like, please leave this conversation, for questions I can have, I will keep in touch.

**Comment by KotlinGeekDev** [comment]
No problem :+1:

**Comment by KotlinGeekDev** [comment]
Library migrated to KMP. Details in #10 .
